const labels = {
  en: {
    newOrders: "New Orders",
    ordersInProduction: "Orders in Production",
    deliveredOrders: "Delivered Orders",
    client: "Client Name",
    clientPlaceholder: "Enter client name",
    orderId: "Order ID",
    quantity: "Quantity",
    fabric: "Fabric Article",
    fabricPlaceholder: "Enter fabric code",
    orderDate: "Order Date",
    orderDateFrom: "Order Date From",
    orderDateTo: "Order Date To",
    deliveryDate: "Delivery Date",
    deliveryDateFrom: "Delivery Date From",
    deliveryDateTo: "Delivery Date To",
    status: "Order Status",
    orderStatus: "Order Status",
    details: "Details",
    qcReport: "QC Report",
    clearFilters: "Clear Filters",
    datePlaceholder: "dd/mm/yyyy",
    noDeliveredOrdersFound: "No delivered orders match your filters."
  },
  sr: {
    newOrders: "Nove Narudžbine",
    ordersInProduction: "Narudžbine u Proizvodnji",
    deliveredOrders: "Isporučene Narudžbine",
    client: "Ime Klijenta",
    clientPlaceholder: "Unesite ime klijenta",
    orderId: "Nalog Broj",
    quantity: "Količina",
    fabric: "Artikal Materijala",
    fabricPlaceholder: "Unesite šifru tkanine",
    orderDate: "Datum Porudžbine",
    orderDateFrom: "Datum Porudžbine Od",
    orderDateTo: "Datum Porudžbine Do",
    deliveryDate: "Datum Isporuke",
    deliveryDateFrom: "Datum Isporuke Od",
    deliveryDateTo: "Datum Isporuke Do",
    status: "Status Naloga",
    orderStatus: "Status Naloga",
    details: "Detalji",
    qcReport: "QC Izveštaj",
    clearFilters: "Obriši Filtere",
    datePlaceholder: "dd/mm/yyyy",
    noDeliveredOrdersFound: "Nema isporučenih narudžbina koje zadovoljavaju filtere."
  }
};

export default labels;
